####
# Process a GregoBase MySQL database dump
# 
# The script extracts all relevant tables as CSV files, and also generates
# a gabc file for every chant in the database. 
#
# Note that the script assumes you have a running mysql installation with
# root access.
#
# Author: Bas Cornelissen
# Date: December 2019
###

### PARAMETERS ################################################################

# File with a dump of the gregobase database
database_dump=$1

# MySQL command; change if you don't have root access
mysql_cmd="mysql -uroot"

# Directories
tmp_dirname="_tmp_mysql_export"
gabc_dirname="gabc"
csv_dirname="csv"

# Temporary database name
dbname="__tmp_db_gregocorpus__"

# CSV field delimiter
field_delimiter="@"



### SETUP #####################################################################

echo "CONVERTING GREGOBASE"
echo "--------------------"

# Create required directories
mkdir -p $csv_dirname
mkdir -p $gabc_dirname
mkdir -p $tmp_dirname

# Fix secure-file-priv issue
echo '> Checking secure-file-priv option'
remove_my_cnf_afterwards=0
if test -f ~/.my.cnf; then 
    echo "  |  The configuration file ~/.my.cnf already exists."
    echo "  |  Please make sure you have secure_file_priv set there; see "
    echo "  |  https://geodatawrangler.lazym8.com/blog/2017/02/16/secure-file-priv"
    echo "  |  for details."

else
    echo "Temporarily fixing secure-file-priv option..."
    echo ">  Creating ~/.my.cnf"

    echo "[mysqld]" > ~/.my.cnf
    echo "secure_file_priv = ''" >> ~/.my.cnf
    remove_my_cnf_afterwards=1
fi



# EXPORT MYSQL DATABASE #######################################################

echo "> Restarting MySQL..."
mysql.server restart

echo "> Creating temporary database: '$dbname'"
statement="create database $dbname;"
eval "$mysql_cmd -e \"$statement\""

echo "> Importing SQL dump: '$database_dump'"
eval "$mysql_cmd $dbname < $database_dump"

echo "> Cleaning up temporary directory: '$tmp_dirname'"
rm -rf $tmp_dirname/*
tmp_dir=$(realpath $tmp_dirname)

echo "> Exporting tables"
echo "  |  Fields are optionally enclosed by '$field_delimiter'. "
echo "  |  Double quotes caused weird errors and are therefore avoided."

options="FIELDS OPTIONALLY ENCLOSED BY '$field_delimiter' TERMINATED BY ',' LINES TERMINATED BY '\n'"
statement="
SELECT * FROM gregobase_chants INTO OUTFILE '$tmp_dir/chants.csv' $options;
SELECT * FROM gregobase_chant_sources INTO OUTFILE '$tmp_dir/chant_sources.csv' $options;
SELECT * FROM gregobase_chant_tags INTO OUTFILE '$tmp_dir/chant_tags.csv' $options;
SELECT * FROM gregobase_sources INTO OUTFILE '$tmp_dir/sources.csv' $options;
SELECT * FROM gregobase_tags INTO OUTFILE '$tmp_dir/tags.csv' $options;"
eval "$mysql_cmd $dbname -e \"$statement\""



#### POST PROCESSING ##########################################################

python post_process_csv.py
python generate_gabc_files.py



#### CLEANING UP ##############################################################

echo "> Cleaning up..."
echo "  |  Remove tmp directory $tmp_dir"
rm -r $tmp_dir

echo "  |  Drop database: $dbname"
statement="drop database $dbname;"
eval "$mysql_cmd -e \"$statement\""

# Only remove configuration file if it has been generated by this script
if (( remove_my_cnf_afterwards > 0 )); then
    echo "  |  Remove ~/.my.cnf"
    rm ~/.my.cnf
else
    echo "  |  Not removing ~/.my.cnf"
fi

echo 'Done.'